config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.htmT

  root "login#authenticate"
  resources :users, except: [:new]
   get '/signup', to: 'users#new'

  match '/login', to: 'login#authenticate', via: [:get, :post]

end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates_presence_of :name, :email, :password
  validates :email, confirmation: { case_sensitive: true }

  after_create :welcome_email

  def welcome_email
    UserMailer.welcome_email(self).deliver
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authorize_request

  def authorize_request
    unless params[:controller].include?("admin")
      if params[:token].present?
        @token = params[:token]
        @decoded = JsonWebToken.decode(@token)
        @current_user = User.find(@decoded[:id])
      end
      unless @current_user.present?
        flash[:notice] = "You are not loged in"
        redirect_to root_path
      end
    end
  end
end

app/controllers/concerns/json_web_token.rb
class JsonWebToken

  SECRET_KEY = Rails.application.secrets.secret_key_base.to_s

  def self.encode(payload, exp = 24.hours.from_now)
    payload[:exp] = exp.to_i
    JWT.encode(payload, SECRET_KEY)
  end

  def self.decode(token)
    decoded = JWT.decode(token, SECRET_KEY)[0]
    HashWithIndifferentAccess.new decoded
  end
end

app/controllers/login_controller.rb
class LoginController < ApplicationController
  skip_before_action :authorize_request

  def authenticate
    unless request.method == "GET"
      user = User.find_by(email: user_params[:email])
      if user.present?
        if user.authenticate(user_params[:password])
          @token = JsonWebToken.encode(id: user.id)
          flash[:success] = "login successful"
          redirect_to users_path(token: @token)
        else
          flash[:notice] = "login failed"
          render :authenticate
        end
      else
        flash[:notice] = "User is not exist"
        redirect_to root_path
      end
    end
  end

  def user_params
    params.require(:user).permit(:email,:password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authorize_request, only: [:create, :new]

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "Registered successfully"
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:success] = "Update data successfully"
      redirect_to users_path
    else
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    flash[:success] = "Delete user data successfully"
    redirect_to users_path
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :address, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(level)
    case level.to_sym
    when :notice then "alert alert-info"
    when :success then "alert alert-success"
    when :error then "alert alert-error"
    when :alert then "alert alert-error"
    end
  end
end

app/views/layouts/_flash_message.html.erb
<div>
  <% flash.each do |key, value| %>
    <div class="<%= flash_class(key) %>">
      <a href="#" data-dismiss="alert" class="close">×</a>
      <%= value %>
    </div>
  <% end %>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-dark">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
        <% if @token.present? %>
          <li class="nav-item active p-2">
            <%= link_to 'Logout', root_path %>
          </li>
        <% else %>
          <li class="nav-item active p-2">
            <%= link_to 'Login', root_path %>
          </li>
          <li class="nav-item active p-2">
            <%= link_to 'Sign up', signup_path %>
          </li>
        <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Project1</title>
    <%= csrf_meta_tags %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= render 'layouts/flash_message' %>
    <%= yield %>
  </body>
</html>

app/views/login/authenticate.html.erb
<%= form_tag(login_path,method: :post) do %>
  <%= label_tag("Email") %>
  <%= text_field :user, :email, required: true %><br>

  <%= label_tag("password") %>
  <%= text_field :user, :password, required: true %><br>

  <%= submit_tag "Login" %><br>

<% end %>

app/views/users/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-dark">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active p-2">
        <%= link_to 'Home', root_path %>
      </li>
      <li class="nav-item active p-2">
        <%= link_to 'Sign in', new_user_path %>
      </li>

      <li class="nav-item active p-2">
        <%= link_to 'Login',new_login_path %>
      </li>
    </ul>
  </div>
</nav>

app/views/users/edit.html.erb
<h1>Edit user data</h1>
<%= form_for @user, method: :patch do |e| %>
  <p>
    <%= e.label :name %><br>
    <%= e.text_field :name %>
  </p>
  <p>
    <%= e.label :email %><br>
    <%= e.text_field :email %>
  </p>
  <p>
    <%= e.label :address %><br>
    <%= e.text_field :address %>
  </p>
  <p>
    <%= e.label :password %><br>
    <%= e.text_field :password %>
  </p>
  <p>
    <%= e.submit("update data") %>
  </p>
<% end %>

app/views/users/index.html.erb
<head>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
</head>
<h1>User list</h1>
<table class="table table-hover table-dark">
  <thead>
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Email</th>
      <th scope="col">Address</th>
    </tr>
  </thead>
  <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= user.name %></td>
          <td><%= user.email %></td>
          <td><%= user.address %></td>
          <td>
            <%= link_to 'show', user_path(id: user.id, token: @token),
            :method => :get, :class => "btn btn-success btn-lg" %>
          </td>
          <td>
            <%= link_to 'Edit', edit_user_path(id: user.id, token: @token),
            :class => "btn btn-success btn-lg" %>
          </td>
          <td>
            <%= link_to 'Delete',user_path(id: user.id, token: @token), method: :delete,
            class: 'btn btn-success btn-lg', data: { confirm: 'are you sure' }%>
          </td>
        </tr>
      <% end %>
  </tbody>
</table>

app/views/users/new.html.erb
<%= form_tag(users_path, method: 'post') do %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@user.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%= label_tag("Name") %>
  <%= text_field(:user, :name) %><br>

  <%= label_tag("Email") %>
  <%= text_field(:user, :email) %><br>

  <%= label_tag("Address") %>
  <%= text_field(:user, :address) %><br>

  <%= label_tag("password") %>
  <%= password_field(:user, :password) %><br>

  <%= submit_tag("sign up")%><br>
  <%= link_to 'back', root_path %>
<% end %>

app/views/users/show.html.erb
<h1>Show page</h1>
<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>
<p>
  <strong>Email id:</strong>
  <%= @user.email %>
</p>
<p>
  <strong>Address:</strong>
  <%= @user.address %>
</p>
<p>
  <strong>password:</strong>
  <%= @user.password %>
</p>
<%= link_to 'back', users_path %>